### ISSUE TITLE
Document how to use the extension in R

### ISSUE THREAD

**Issue by romainfrancois** [krlmlr/duckdb-rfuns#2]
Based on https://duckdb.org/docs/archive/0.9.2/extensions/overview, update the README to document how to use this extension in R.

**Comment by romainfrancois** [comment]
so far, I'm at: 

```
dbExecute(con, "LOAD '/Users/romainfrancois/work/cynkra/duckdb-rfuns/build/release/extension/rfuns/rfuns.duckdb_extension'")
Error: rapi_execute: Failed to run query
Error: Invalid Input Error: Extension "/Users/romainfrancois/work/cynkra/duckdb-rfuns/build/release/extension/rfuns/rfuns.duckdb_extension" version (v0.9.2) does not match DuckDB version (v0.0.0)
```

Will investigate more. 

I also see the `DUDKDB_R_EXTENSIONS` environment variable in `rconfigure.py` : 

```
# check if there are any additional extensions being requested
if 'DUCKDB_R_EXTENSIONS' in os.environ:
    extensions = extensions + os.environ['DUCKDB_R_EXTENSIONS'].split(",")
```

that's probably relevant

**Comment by krlmlr** [comment]
How did you install duckdb?

**Comment by romainfrancois** [comment]
I have `pak::pak()` from the cloned `duckdb-r` repo, following https://github.com/duckdb/duckdb-r#building 

I'll try without the `./vendor.sh` bit, but then I'm not sure this sets the `EXTENSION_STATIC_BUILD`, I'll investigate/get familiar some more.

**Comment by krlmlr** [comment]
Can you try with duckdb from CRAN?

Romain François ***@***.***> schrieb am Mi. 17. Jan. 2024 um
12:16:

**Comment by romainfrancois** [comment]
update. I've reinstalled `duckdb` locally with a `pak::pak("duckdb")` and then reinstalled the extension from a fresh clone, and that seems to work now: 

```R
library(duckdb)
con <- DBI::dbConnect(duckdb(config=list('allow_unsigned_extensions'='true')))
dbExecute(con, "LOAD '/Users/romainfrancois/work/cynkra/duckdb-rfuns/build/release/extension/rfuns/rfuns.duckdb_extension'")
dbGetQuery(con, "select rfuns('Jane')")
```

gives: 

<img width="1026" alt="image" src="https://github.com/krlmlr/duckdb-rfuns/assets/2625526/1879c82a-b783-45ff-8136-436d835361ac">

I'll get started on a pr to update the README 🦆
