### ISSUE TITLE
Structure as an R package

### ISSUE THREAD

**Issue by romainfrancois** [krlmlr/duckdb-rfuns#5]
To ease development. 

The 📦 could have host the extension somewhere in `inst` so that we can have something easier than: 

```r
dbExecute(con, "LOAD '{{path to duckdb-rfuns}}/build/release/extension/rfuns/rfuns.duckdb_extension'")
```

**Comment by krlmlr** [comment]
Agreed, but let's keep the general structure of this repository, for CI/CD.

**Comment by romainfrancois** [comment]
Sure. I was thinking perhaps : 
 - The 📦 lives in e.g. `r/`
 - `make` could move `rfuns.duckdb_extension` somewhere in `r/inst` of the package. 
 - The 📦 loads it because it finds it with `system.file()` ...

I think it's fine if it's a little quirky, because IIUC the endgame is for the extension to be `LOAD` in `duckplyr` but at least having a package here gives some structure we can leverage for e.g. test that etc ...

**Comment by krlmlr** [comment]
Works for me. Thanks!
