### ISSUE TITLE
Show more descriptive name in caption of RStudio IDE

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/duckdb-rfuns#9]
The project is started from the `r` directory, as a result, the RStudio IDE shows only "r" in a caption. Is there a way to configure this?

As a last resort, rename `r` to `duckdb-rfuns-r`, even if it's redundant.

**Comment by romainfrancois** [comment]
🤔 I'm not sure. I'll do go with `duckdb-rfuns-r` for now
